
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNLE'
  name: 'toy_SNLE'
  nets:
    - model: 'maf'
      signature: ''
      hidden_features: 50 
      num_transforms: 6
    - model: 'mdn'
      signature: ''
      hidden_features: 50 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
