backend: 'pydelfi'

meta_path: './toy/toy_pydelfi_posterior.pkl'
output_path: './toy'
labels: ['t1', 't2', 't3']

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1500
      sample_method: 'emcee'
      sample_params:
        num_chains: 10
        burn_in: 100
        thin: 10

