
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNLE'
  neural_posteriors:
    - model: 'maf'
      hidden_features: 50 
      num_transforms: 5
    - model: 'mdn'
      hidden_features: 50 
      num_components: 2
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
