
prior:
  module: 'ili.utils'
  class: 'BoxUniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNRE'
  nets:
    - model: 'resnet'
      hidden_features: 50
      num_blocks: 3
    - model: 'mlp'
      hidden_features: 50
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
