posterior_path: './toy/posterior.pkl'
output_path: './toy'

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1000
      labels: ['t1', 't2', 't3']

  tarp:
    module: 'ili.validation.metrics'
    class: 'TARP'
    args:
      num_samples: 100

  rank_stats:
    module: 'ili.validation.metrics'
    class: 'PlotRankStatistics'
    args:
      num_samples: 100
      labels: ['t1', 't2', 't3']
