backend: 'sbi'

posterior_path: './toy/posterior.pkl'
output_path: './toy'
labels: ['t1', 't2', 't3']

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1000
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 1
        burn_in: 100
        thin: 10

  rank_stats:
    module: 'ili.validation.metrics'
    class: 'PlotRankStatistics'
    args:
      num_samples: 100
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 1
        burn_in: 100
        thin: 1

  tarp:
    module: 'ili.validation.metrics'
    class: 'TARP'
    args:
      num_samples: 10
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 1
        burn_in: 100
        thin: 1
