posterior_file: 'toy_SNLE_posterior.pkl'  # Path to posterior model
out_dir: './toy'  # Where to save the metrics
labels: ['t1', 't2', 't3']  # Names of the parameters

# If True, run validation for all networks as one ensemble posterior
# If False, run validation for each network separately
ensemble_mode: True

metrics:
  # Plot an example posterior for a single input
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1200
      sample_method: 'slice_np_vectorized'  # MCMC slice sampling (pyro backend)
      sample_params:
        num_chains: 1
        burn_in: 100
        thin: 10

  # Compute and plot coverage metrics across the test set
  coverages:
    module: 'ili.validation.metrics'
    class: 'PosteriorCoverage'
    args:
      save_samples: True
      num_samples: 1000
      sample_method: 'vi'
      sample_params:
        dist: 'maf'
        n_particles: 32
        learning_rate: 0.01
      plot_list: ["coverage", "histogram", "predictions", "tarp"]
